WebFormsDM/WebFormsDM.Web/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using WebFormsDM.Data.Entities;
using WebFormsDM.Services.Contracts;
using WebFormsDM.Web.Models;
using WebFormsDM.Web.ViewModelsMapper;

namespace WebFormsDM.Web.Controllers
{
    public class FormsController : Controller
    {
        private readonly IFormService formServices;
        private readonly UserManager<User> userManager;
        private readonly IToastNotification toastNotification;

        public FormsController(IFormService formServices,
                               UserManager<User> userManager,
                               IToastNotification toastNotification)
        {
            this.formServices = formServices ?? throw new ArgumentNullException(nameof(formServices));
            this.userManager = userManager;
            this.toastNotification = toastNotification;
        }

        [HttpGet]
        public IActionResult Create()
        {
            var formViewModel = new FormViewModel();
            return View(formViewModel);
        }
        [HttpPost]
        public async Task Create(FormViewModel formViewModel)
        {
            if (!ModelState.IsValid)
            {
                //this.toastNotification.AddWarningToastMessage($"Something went wrong!");
            }
            try
            {
                formViewModel.UserId = (await userManager.GetUserAsync(User)).Id;

                foreach (var optionsQuestion in formViewModel.OptionQuestions)
                {
                    foreach (var option in optionsQuestion.OptionsAsString)
                    {
                        if(option != null)
                        {
                            var oQ = new OptionsQuestionOptionViewModel();
                            oQ.Option = option;
                            optionsQuestion.Options.Add(oQ);
                        }
                    }
                }
               var formDto = formViewModel.GetDto();

               var newForm = await this.formServices.CreateFormAsync(formDto);

                this.toastNotification.AddWarningToastMessage($"The form has been created!");
            }
            catch (Exception)
            {
                this.toastNotification.AddWarningToastMessage($"Something went wrong!");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var formDto = await this.formServices.GetFormAsync(id);

                if (formDto == null)
                {
                    return NotFound();
                }

                var formViewModel = formDto.GetViewModel();


                return View(formViewModel);
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task Edit(FormViewModel formViewModel)
        {
  
            try
            {
                formViewModel.UserId = (await userManager.GetUserAsync(User)).Id;

                foreach (var optionsQuestion in formViewModel.OptionQuestions)
                {
                    foreach (var option in optionsQuestion.OptionsAsString)
                    {
                        if (option != null)
                        {
                            var oQ = new OptionsQuestionOptionViewModel();
                            oQ.Option = option;
                            optionsQuestion.Options.Add(oQ);
                        }
                    }
                }
                var formDto = formViewModel.GetDto();

                var newForm = await this.formServices.CreateNewVersionOfFormAsync(formDto);

                var newformViewModel = newForm.GetViewModel();


            }
            catch (Exception)
            {
                this.toastNotification.AddWarningToastMessage($"Something went wrong!");
            }

        }
        [HttpGet]
        public async Task<IActionResult> GetFormWithAnswers(Guid id)
        {
            var formDto = await this.formServices.GetFormWithAnswersAsync(id);
            var formVM = formDto.GetViewModel();

            return View(formVM);
        }

        [HttpGet]
        public async Task<IActionResult> GetFormWithOneAnswer(Guid formId, Guid correlationToken)
        {
            var formDto = await this.formServices.GetFromWithOneAnswerAsync(formId, correlationToken);
            var fromVM = formDto.GetViewModel();

            return View(fromVM);
        }
    

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = (await userManager.GetUserAsync(User)).Id;
            var allUserForms = await this.formServices.GetUserFormsAsync(userId);
            var allUserFormsVM = allUserForms.GetViewModels();

            return View(allUserFormsVM);
        } 

    }

}

WebFormsDM/WebFormsDM.Web/Views/Shared/_FormWithAnswersPartial.cshtml
@model WebFormsDM.Web.Models.FormViewModel

@{
    ViewData["Title"] = "_FormWithAnswersPartial";
}

<style>
    h4 {
        text-align: center;
    }

    h5 {
        text-align: center;
    }
</style>

<div class="card card-body">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <h4 class="card-title">@Model.Title</h4>
    <h5 class="card-subtitle mb-2 text-muted">@Model.Description</h5>
    <br />
    <br />
    <div class="col-sm-12" id="questionContainer">
        @{
            var currentToken = Model.AllCorrelationTokens.FirstOrDefault();
            int counter = 1;
            int optionQuestionCounter = 1;
            //int optionsCounter = 1;
            int documentQuestionCounter = 1;
            //int allQuestionsCount = Model.TextQuestions.Count
            //                      + Model.OptionQuestions.Count
            //                      + Model.DocumentQuestions.Count;
            int textQMaxOrderNumber = 0;
            int optionQMaxOrderNumber = 0;
            int documentQMaxOrderNumber = 0;

            if (Model.TextQuestions.Count != 0)
            {
                textQMaxOrderNumber = Model.TextQuestions.LastOrDefault().OrderNumber;
            }

            if (Model.OptionQuestions.Count != 0)
            {
                optionQMaxOrderNumber = Model.OptionQuestions.LastOrDefault().OrderNumber;
            }

            if (Model.DocumentQuestions.Count != 0)
            {
                documentQMaxOrderNumber = Model.DocumentQuestions.LastOrDefault().OrderNumber;
            }

            int maxOrderNumber = textQMaxOrderNumber;

            if (optionQMaxOrderNumber > textQMaxOrderNumber && optionQMaxOrderNumber > documentQMaxOrderNumber)
            {
                maxOrderNumber = optionQMaxOrderNumber;
            }
            else if (documentQMaxOrderNumber > textQMaxOrderNumber && documentQMaxOrderNumber > optionQMaxOrderNumber)
            {
                maxOrderNumber = documentQMaxOrderNumber;
            }
        }

        @for (int i = 1; i <= maxOrderNumber; i++)
        {

            for (int j = 0; j < Model.TextQuestions.Count; j++)
            {
                if (Model.TextQuestions[j].OrderNumber == i)
                {
                    <div class="form-group" id="QuestionID_@i">
                        @*<div class="form-group">*@
                        <input value="@Model.TextQuestions[j].Description" class="form-control" id="textQuestionDescription_@counter" readonly />
                        <input type="hidden" id="OrderNumber_@counter" name="OrderNumber" value="@Model.TextQuestions[j].OrderNumber">
                        <div class="form-group">
                            <br />
                            <div class="custom-control custom-switch">
                                <input asp-for="@Model.TextQuestions[j].IsRequired" type="checkbox" class="custom-control-input" id="IsRequiredTextQuestion_@counter" disabled="disabled">
                                <label class="custom-control-label" for="IsRequiredTextQuestion_@counter">Required</label>
                            </div>
                            @for (int k = 0; k < Model.TextQuestions[j].Answers.Count; k++)
                            {
                                if (Model.TextQuestions[j].Answers.ToList()[k].CorrelationToken == currentToken)
                                {
                                    <input value="@Model.TextQuestions[j].Answers.ToList()[k].Answer" class="form-control" id="textQuestionAnswer_@counter" readonly />
                                }
                            }
                        </div>
                        <br />
                    </div>
                    @*</div>*@
                    counter++;
                    break;
                }
            }

            for (int k = 0; k < Model.OptionQuestions.Count; k++)
            {
                if (Model.OptionQuestions[k].OrderNumber == i)
                {

                    <div class="form-group" id="QuestionID_@i">
                        @*<div class="form-group">*@
                        <input value="@Model.OptionQuestions[k].Description" class="form-control" id="optionQuestionDescription_@optionQuestionCounter" readonly />
                        <input type="hidden" id="OrderNumberOQ_@optionQuestionCounter" name="OrderNumber" value="@Model.OptionQuestions[k].OrderNumber">
                        <div class="form-group">
                            <div class="custom-control custom-switch">
                                <input asp-for="@Model.OptionQuestions[k].IsRequired" type="checkbox" class="custom-control-input" id="IsRequiredOptionQuestion_@optionQuestionCounter" disabled="disabled">
                                <label class="custom-control-label" for="IsRequiredOptionQuestion_@optionQuestionCounter">Required</label>
                                <span asp-validation-for="@Model.OptionQuestions[k].IsRequired" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-11" id="add_@optionQuestionCounter">
                                    @for (int m = 0; m < Model.OptionQuestions[k].Options.Count; m++)
                                    {
                                        for (int n = 0; n < Model.OptionQuestions[k].Answers.Count; n++)
                                        {
                                            if (Model.OptionQuestions[k].Answers.ToList()[n].CorrelationToken == currentToken)
                                            {
                                                var optionQuestonAswers = Model.OptionQuestions[k].Answers.ToList()[n].Answer.Split(",").ToList();

                                                if (Model.OptionQuestions[k].IsAllowedMultipleAnswers == false)
                                                {

                                                    for (int p = 0; p < optionQuestonAswers.Count; p++)
                                                    {
                                                        if (optionQuestonAswers[p] == Model.OptionQuestions[k].Options[m].Option)
                                                        {
                                                            <div class="form-check">
                                                                <input type="radio" class="form-check-input" id="materialGroupExample2" name="groupOfMaterialRadios_@optionQuestionCounter" value="Y" checked disabled>
                                                                <label class="form-check-label" for="@Model.OptionQuestions[k].Options[m].Option">@Model.OptionQuestions[k].Options[m].Option</label>
                                                            </div>
                                                        }
                                                        else
                                                        {
                                                            <div class="form-check">
                                                                <input type="radio" class="form-check-input" id="materialGroupExample2" name="groupOfMaterialRadios_@optionQuestionCounter" value="N" disabled>
                                                                <label class="form-check-label" for="@Model.OptionQuestions[k].Options[m].Option">@Model.OptionQuestions[k].Options[m].Option</label>
                                                            </div>
                                                        }
                                                    }
                                                }
                                                else
                                                {
                                                    if (optionQuestonAswers.Contains(Model.OptionQuestions[k].Options[m].Option))
                                                    {
                                                        <!-- Default checked -->
                                                        <div class="custom-control custom-checkbox">
                                                            <input type="checkbox" class="custom-control-input" id="defaultChecked2" disabled="disabled" checked>
                                                            <label class="custom-control-label" for="@Model.OptionQuestions[k].Options[m].Option">@Model.OptionQuestions[k].Options[m].Option</label>
                                                        </div>
                                                    }
                                                    else
                                                    {
                                                        <!-- Default checked -->
                                                        <div class="custom-control custom-checkbox">
                                                            <input type="checkbox" class="custom-control-input" id="DefaultUncheckeds" disabled="disabled">
                                                            <label class="custom-control-label" for="@Model.OptionQuestions[k].Options[m].Option">@Model.OptionQuestions[k].Options[m].Option</label>
                                                        </div>
                                                    }
                                                }
                                            }
                                        }
                                    }
                                </div>
                            </div>
                        </div>
                        <br />
                    </div>
                    @*</div>*@
                    optionQuestionCounter++;
                    break;
                }
            }


            for (int n = 0; n < Model.DocumentQuestions.Count; n++)
            {

                if (Model.DocumentQuestions[n].OrderNumber == i)
                {
                    <div class="form-group" id="QuestionID_@i">
                        @*<div class="form-group">*@
                        <input value="@Model.DocumentQuestions[n].Description" class="form-control" id="documentQuestionDescription_@documentQuestionCounter" readonly />
                        <input type="hidden" id="OrderNumberDQ_@documentQuestionCounter" name="OrderNumber" value="@Model.DocumentQuestions[n].OrderNumber">
                        <div class="custom-control custom-switch">
                            <input asp-for="@Model.DocumentQuestions[n].IsRequired" type="checkbox" class="custom-control-input" id="IsRequiredTextQuestion_@documentQuestionCounter" disabled="disabled">
                            <label class="custom-control-label" for="IsRequiredTextQuestion_@counter">Required</label>
                        </div>

                        @for (int j = 0; j < Model.DocumentQuestions[n].Answers.Count; j++)//j
                        {
                            if (Model.DocumentQuestions[n].Answers.ToList()[j].CorrelationToken == currentToken)
                            {
                                for (int k = 0; k < Model.DocumentQuestions[n].Answers.ToList()[j].FileAnswers.Count; k++)
                                {

                                    var currentPath = Model.DocumentQuestions[n].Answers.ToList()[j].FileAnswers.ToList()[k].FilePath;
                                    var pFileName = currentPath.Split('_').Last();
                                    <br />
                                    <div class="form-group">
                                        <div class="btn btn-outline-info">
                                            <a href="@currentPath" download="@pFileName">Download</a>
                                        </div>
                                    </div>

                                }
                            }
                        }

                        <br />
                    </div>
                    @*</div>*@
                    documentQuestionCounter++;
                    break;
                }
            }
        }
    </div>
</div>

WebFormsDM/WebFormsDM.Web/Views/Shared/_Layout.cshtml
@await Component.InvokeAsync("NToastNotify")
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebFormsDM.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a href="https://localhost:44342/"><img id="logo" src="~/Images/WFLogo.jpg" height="45" width="113" /></a>

                @*<img src="~/Images/WFLogo.jpg" height="45" width="113" />
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>*@
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Forms" asp-action="Index">Forms</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Forms" asp-action="Create">Create Form</a>
                            </li>

                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <style>
        body {
            background-image: url('/Images/BackgroundLight.jpg');
            background-repeat: no-repeat;
        }
    </style>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebFormsDM.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script>function test() { console.log("test") }</script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebFormsDM/WebFormsDM.Web/Views/Shared/_NoAnswersPartial.cshtml
@model WebFormsDM.Web.Models.FormViewModel


<img src="~/Images/NoAnswersYet.png" height="463" width="1100" alt="No answers yet!" />
<br />
@*<p align="center">
    <a asp-controller="FillForm" asp-action="Fill" asp-route-id="@Model.Id" class="btn btn-outline-info">Back To Form</a>
</p>*@