WebFormsDM/WebFormsDM.Web/Models/FormViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebFormsDM.Web.Models
{
    public class FormViewModel
    {
        public FormViewModel()
        {
            this.TextQuestions = new List<TextQuestionViewModel>();
            this.OptionQuestions = new List<OptionQuestionsViewModel>();
            this.DocumentQuestions = new List<DocumentQuestionViewModel>();
            this.AllCorrelationTokens = new List<Guid>();
            //this.Questions = new Questions();
        }
        public Guid Id { get; set; }   
        [Required]
        [MaxLength(150)]
        public string Title { get; set; }
        public string Description { get; set; }
        public int NumberOfFilledForms { get; set; }
        public Guid UserId { get; set; }
        public DateTime CreatedOn { get; set; } = DateTime.UtcNow;
        public DateTime DateOfExpiration { get; set; }
        public DateTime? LastModifiedOn { get; set; } = DateTime.UtcNow;
        public bool IsDeleted { get; set; }
        
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string RecipientOfTheSurvey { get; set; }

        //public User User { get; set; }
        public List<TextQuestionViewModel> TextQuestions { get; set; }
        public List<OptionQuestionsViewModel> OptionQuestions { get; set; }
        public List<DocumentQuestionViewModel> DocumentQuestions { get; set; }
        public ICollection<Guid> AllCorrelationTokens { get; set; }
        //public Questions Questions { get; set; }
    }

}

WebFormsDM/WebFormsDM.Web/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using WebFormsDM.Data.Entities;
using WebFormsDM.Services.Contracts;
using WebFormsDM.Web.Models;
using WebFormsDM.Web.ViewModelsMapper;

namespace WebFormsDM.Web.Controllers
{
    public class FormsController : Controller
    {
        private readonly IFormService formServices;
        private readonly UserManager<User> userManager;
        private readonly IToastNotification toastNotification;

        public FormsController(IFormService formServices,
                               UserManager<User> userManager,
                               IToastNotification toastNotification)
        {
            this.formServices = formServices ?? throw new ArgumentNullException(nameof(formServices));
            this.userManager = userManager;
            this.toastNotification = toastNotification;
        }

        [HttpGet]
        public IActionResult Create()
        {
            var formViewModel = new FormViewModel();
            return View(formViewModel);
        }
        [HttpPost]
        public async Task Create(FormViewModel formViewModel)
        {
            if (!ModelState.IsValid)
            {
                //this.toastNotification.AddWarningToastMessage($"Something went wrong!");
            }
            try
            {
                formViewModel.UserId = (await userManager.GetUserAsync(User)).Id;

                foreach (var optionsQuestion in formViewModel.OptionQuestions)
                {
                    foreach (var option in optionsQuestion.OptionsAsString)
                    {
                        if(option != null)
                        {
                            var oQ = new OptionsQuestionOptionViewModel();
                            oQ.Option = option;
                            optionsQuestion.Options.Add(oQ);
                        }
                    }
                }
               var formDto = formViewModel.GetDto();

               var newForm = await this.formServices.CreateFormAsync(formDto);

                this.toastNotification.AddWarningToastMessage($"The form has been created!");
            }
            catch (Exception)
            {
                this.toastNotification.AddWarningToastMessage($"Something went wrong!");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var formDto = await this.formServices.GetFormAsync(id);

                if (formDto == null)
                {
                    return NotFound();
                }

                var formViewModel = formDto.GetViewModel();


                return View(formViewModel);
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task Edit(FormViewModel formViewModel)
        {
  
            try
            {
                formViewModel.UserId = (await userManager.GetUserAsync(User)).Id;

                foreach (var optionsQuestion in formViewModel.OptionQuestions)
                {
                    foreach (var option in optionsQuestion.OptionsAsString)
                    {
                        if (option != null)
                        {
                            var oQ = new OptionsQuestionOptionViewModel();
                            oQ.Option = option;
                            optionsQuestion.Options.Add(oQ);
                        }
                    }
                }
                var formDto = formViewModel.GetDto();

                var newForm = await this.formServices.CreateNewVersionOfFormAsync(formDto);

                var newformViewModel = newForm.GetViewModel();


            }
            catch (Exception)
            {
                this.toastNotification.AddWarningToastMessage($"Something went wrong!");
            }

        }
        [HttpGet]
        public async Task<IActionResult> GetFormWithAnswers(Guid id)
        {
            var formDto = await this.formServices.GetFormWithAnswersAsync(id);
            var formVM = formDto.GetViewModel();

            return View(formVM);
        }

        [HttpGet]
        public async Task<IActionResult> GetFormWithOneAnswer(Guid formId, Guid correlationToken)
        {
            var formDto = await this.formServices.GetFromWithOneAnswerAsync(formId, correlationToken);
            var fromVM = formDto.GetViewModel();

            return View(fromVM);
        }
    

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = (await userManager.GetUserAsync(User)).Id;
            var allUserForms = await this.formServices.GetUserFormsAsync(userId);
            var allUserFormsVM = allUserForms.GetViewModels();

            return View(allUserFormsVM);
        } 

    }

}

WebFormsDM/WebFormsDM.Web/Controllers/SendSurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using WebFormsDM.Web.Models;

namespace WebFormsDM.Web.Controllers
{
    public class SendSurveyController : Controller
    {
        private readonly IToastNotification toastNotification;

        public SendSurveyController(IToastNotification toastNotification)
        {
            this.toastNotification = toastNotification;
        }

        public IActionResult SendSurveyByEmail(FormViewModel form)
        {
            try
            {
                string sendTo = form.RecipientOfTheSurvey;
                MailMessage mail = new MailMessage();
                mail.To.Add(sendTo);
                mail.Subject = "Survey";
                mail.Body = "https://localhost:44342/FillForm/Fill/" + form.Id;
                mail.From = new MailAddress("dobromirbonevff@gmail.com");
                mail.IsBodyHtml = false;
                SmtpClient smtp = new SmtpClient("smtp.gmail.com");
                smtp.Port = 587;
                smtp.UseDefaultCredentials = true;
                smtp.EnableSsl = true;
                smtp.Credentials = new System.Net.NetworkCredential("webformsdm@gmail.com", "WebForms1");
                smtp.Send(mail);
            }
            catch (Exception)
            {
                this.toastNotification.AddWarningToastMessage($"Something went wrong!");
                return Redirect("/Forms/Index");
            }


            this.toastNotification.AddInfoToastMessage($"The survey was successfully sent");
            return Redirect("/Forms/Index");
        }
    }
}

WebFormsDM/WebFormsDM.Web/Views/Forms/Create.cshtml
@model WebFormsDM.Web.Models.FormViewModel

@{
    ViewData["Title"] = "Create";

}

<h1>Create Form</h1>

<hr />
<br/>
<div class="row">
    <div class="col-md-11">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <input asp-for="Title" class="form-control" placeholder="Untitled form" id="formTitle" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Description" class="form-control" placeholder="Description" id="formDescription" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="col-sm-12" id="questionContainer">

        </div>
        <br />
        <div class="row">
            <div class="col-md-4">
                <input class="btn btn-outline-info" type="button" id="btnAddTextQ" value="Add Text Question" />
            </div>
            <div class="col-md-4">
                <input class="btn btn-outline-info" type="button" id="btnAddOptionQ" value="Add Option Question" />
            </div>
            <div class="col-md-4">
                <input class="btn btn-outline-info" type="button" id="btnAddDocumentQ" value="Add Document Question" />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4">
                <button id="submitFormViewModel" onclick="create()" type="submit" value="Create" class="btn btn-info">Create</button>
            </div>
        </div>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/createForm.js"></script>

}

WebFormsDM/WebFormsDM.Web/Views/Forms/GetFormWithAnswers.cshtml
@model WebFormsDM.Web.Models.FormViewModel
@{
    ViewData["Title"] = "GetFormWithAnswers";
}




<br />

<div class="col-sm-12">
    @if (Model.AllCorrelationTokens.Count == 0)
    {
       @await Html.PartialAsync("_NoAnswersPartial")
        
    }
    else
    {
        <form>
            <div class="dropdown pull-right" id="responseNumber">
                <label class="control-label">
                    @*File Size*@
                    <select class="form-control" name="correlationToken">
                        @for (int i = 0; i < Model.AllCorrelationTokens.Count; i++)
                        {
                            int responseNumber = i + 1;
                            <option value="@Model.AllCorrelationTokens.ToList()[i]">Response @responseNumber</option>
                        }
                    </select>
                </label>
                <input type="hidden" value="@Model.Id" name="formId" />
            </div>
            <br />
            <input type="submit" asp-action="GetFormWithOneAnswer" value="View Answer" class="btn btn-outline-info">
        </form>
        <br />
        <br />
        @await Html.PartialAsync("_FormWithAnswersPartial")
        <br />
    }
</div>
<div class="col-md-1">
    <form>
        <input type="hidden" value="@Model.Id" name="id" />
        <input type="submit" asp-controller="FillForm" asp-action="Fill" value="Back" class="btn btn-info" />
    </form>
</div>




@section Scripts{
    <script>
        $('#responseNumber').change(function () {
            var response = $('#responseNumber option:selected').val();

            console.log(response);
            /* $('#hiddenselectedwifivalue').val(selectedwifi);*/ //set value of hidden field


        });
    </script>
}

WebFormsDM/WebFormsDM.Web/Views/Forms/GetFormWithOneAnswer.cshtml
@model WebFormsDM.Web.Models.FormViewModel
@{
    ViewData["Title"] = "GetFormWithOneAnswer";
}

   
<br />
<br />
@await Html.PartialAsync("_FormWithAnswersPartial")
<br />
<div class="col-md-1">
    <form>
        <input type="hidden" value="@Model.Id" name="id" />
        <input type="submit" asp-action="GetFormWithAnswers" value="Back" class="btn btn-info" />
    </form>
</div>

WebFormsDM/WebFormsDM.Web/Views/Forms/Index.cshtml
@model IEnumerable<WebFormsDM.Web.Models.FormViewModel>

@{
    ViewData["Title"] = "ListForms";
}

<br/>
<br/>
<div class="text-center">
    <h4>My Forms</h4>
</div>

<br />
<br />

<div class="card-deck">
    @foreach (var item in Model)
    {
        <div class="col-sm-4">
            <div class="card text-center bg-white " style="width: 18rem; ">
                <div class="card-body">
                    <h5 class="card-title">@item.Title</h5>
                    <br />
                    <p class="card-text">
                        Created on:
                        <br />
                        @item.CreatedOn
                    </p>
                    <p class="card-text">
                        Current answers count:
                        <br />
                        @item.NumberOfFilledForms
                    </p>
                </div>
                <div class="card-footer">
                    <a asp-area="" asp-controller="FillForm" asp-action="Fill" asp-route-id="@item.Id" class="btn btn-info">Preview</a>

                    <input type="button" value="Share" class="btn btn-info" data-name="@item.Title" data-id="@item.Id" id="sendButton" data-toggle="modal" data-target="#exampleModal" />
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Send survey: @item.Title</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form asp-controller="SendSurvey" asp-action="SendSurveyByEmail">
                                        <input value="@item.Id" name="Id" type="hidden" id="hiddenId" />
                                        <div class="form-group">
                                            <label for="message-text" class="col-form-label">Recipient:</label>
                                            <input class="form-control" asp-for="@item.RecipientOfTheSurvey" name="RecipientOfTheSurvey" id="message-text" required />
                                            <span asp-validation-for="@item.RecipientOfTheSurvey" class="text-danger"></span>
                                        </div>
                                        <button type="button" class="btn btn-outline-info" data-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-info" value="Send">Send</button>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <br />
            <br />
        </div>

    }
</div>
@section Scripts {
    <script>
        $(function () {
            $(document).on('click', '#sendButton', function (x) {
                x.preventDefault();
                let title = $(this).data("name");
                let formId = $(this).data("id");
                $("#exampleModalLabel").html("Send survey: " + title);
                $("#hiddenId").removeAttr("value");
                $("#hiddenId").attr("value", formId);

                console.log(title);
                console.log(formId);

            });
        });
    </script>
}